/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const pdfhandler_Logic = require('./code/pdfhandler-logic');
const uploadchunk_Logic = require('./code/uploadchunk-logic');
const assemblefile_Logic = require('./code/assemblefile-logic');

class pdfService extends LCAPApplicationService {
    async init() {

        this.on('PdfHandler', async (request) => {
            return pdfhandler_Logic(request);
        });

        this.on('uploadChunk', async (request) => {
            return uploadchunk_Logic(request);
        });

        this.on('assembleFile', async (request) => {
            return assemblefile_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    pdfService
};